const { SlashCommandBuilder } = require('@discordjs/builders');

function descriptor(){
   var d = [
		"barbaric",
		"tribal",
		"savage",
		"wicked",
		"evil",
		"oozing",
		"painted",
		"beastly",
		"angelic",
		"divine",
		"mystical",
		"spurned",
		"outlaw",
		"reckless",
		"carefree",
		"celestial",
		"jovial",
		"miserable",
		"stoic",
		"fearful",
		"nasty",
		"sexy",
		"cool",
		"explosive",
		"short-tempered",
		"screaming",
		"stealthy",
		"devilish",
		"demonic",
		"undead",
		"magical",
		"cunning",
		"druidic",
		"natural",
		"dungeon-dwelling",
		"enchanted",
		"fey",
		"zombie",
		"slime",
		"sword-wielding",
		"wizardy",
		"whimsical",
		"ancient",
		"eldritch",
		"roaring",
		"flame-covered",
		"elemental",
		"romantic",
		"miserable",
		"spry",
		"flexible",
		"taunting",
		"cute",
		"cruel",
		"portly",
		"skinny",
		"somber",
		"strong",
		"graceful",
		"nimble",
		"heroic",
		"piratey",
		"happy-go-lucky",
		"neat",
		"educated",
		"sleepy",
		"horny",
		"kindhearted",
		"helpless",
		"goth",
		"impractically-armored",
		"scantily-clad",
		"urban",
		"noble",
		"short",
		"shadowy",
		"royal",
		"playful",
		"monstrous",
		"wise",
		"idiotic",
		"mundane",
		"alarmed",
		"bitter",
		"sick",
		"klutzy",
		"archtypical",
		"bizarro",
		"dream-like",
		"celebrating",
		"bimbo/himbo",
		"muscular",
		"heavyset",
		"camoflauged",
		"exotic",
		"bardic",
		"scifi",
		"dystopian",
		"fungal",
		"weird",
		"bog",
		"forest",
		"desert",
		"arctic",
		"grassland",
		"volcanic",
		"cyberpunk",
		"split-dress wearing",
		"poncho-wearing",
		"shibari-bondaged",
		"arm-length glove & thigh-high-wearing",
		"big-sword-wielding",
		"pasties/tape-wearing",
		"bottomless",
		"scary-clawed",
		"embarassed nude",
		"functionally naked",
		"groped by phantom hands",
		"wrist/arm wrap-wearing",
		"muzzled/ballgagged",
		"wardrobe-malfunctioned",
		"petplaying/collared",
		"dynamically-attacking",
		"fancily outfitted",
		"post-fight",
		"cool-jacket-wearing",
		"skintight bodysuit-wearing",
		"bodypainted/tribally-marked",
		"\"Everybody is so mean to me\"-esque",
		"androgynous",
		"unusual",
		"scarred",
		"haunted",
		"goofy",
		"topless",
		"trans",
		"sharp-toothed",
		"well-endowed",
		"lanky",
		"bound",
		"sappy",
		"gleeful",
		"flawless",
		"stupid",
		"ditzy",
		"p-shaped",
		"big bottomed",
		"ridiculous",
		"kind-hearted",
		"sinister",
		"concerned",
		"confused",
		"grand",
		"tired",
		"angry",
		"drunk",
		"happy",
		"sad",
		"silly",
		"serious",
		"confident",
		"sarcastic",
		"roided-out",
		"high"
		
    ]

    return d[getRandomInt(d.length -1)];
}

function noun(){
	var n = [
		"[one of your OCs]",
		"[a friend's OC]",
		"[someone in the call's OC]",
		"[media character you like]",
		"creature",
		"beast",
		"kobold",
		"femboy",
		"tomboy",
		"ghost",
		"bird",
		"crocodile",
		"orc",
		"elf",
		"dwarf",
		"halfling",
		"rat", 
		"cat", 
		"bat", 
		"lizard", 
		"dragon", 
		"robot", 
		"dog", 
		"fox", 
		"golem", 
		"skunk",
		"plantfolk",
		"bug",
		"gnoll",
		"alien",
		"skeleton",
		"sonic oc",
		"yinglet",
		"aeromorph",
		"fish",
		"snail",
		"puppet",
		"pokemon",
		"chimera",
		"kangaroo",
		"shark",
		"horse",
		"pony",
		"porcupine",
		"mouse",
		"hippo",
		"goblin",
		"ant",
		"bee",
		"boar",
		"mimic",
		"turtle",
		"hedgehog",
		"monkey",
		"serpent",
		"stoat",
		"unicorn",
		"tiefling",
		"gnome",
		"satyr",
		"harpy",
		"merfolk",
		"undead",
		"vampire",
		"carnivore",
		"apex-predator",
		"herbivore",
		"bull",
		"seal",
		"argonian",
		"khajiit",
		"coyote",
		"spider",
		"humanoid",
		"panda",
		"wolf",
		"rabbit",
		"tiger",
		"reptile",
		"bear",
		"deer",
		"lion",
		"goat",
		"ram",
		"sheep",
		"dinosaur",
		"human",
		"raccoon",
		"tanuki",
		"husky",
		"troll",
		"hellhound",
		"red panda",
		"living-weapon",
		"tv-headed",
		"object-headed",
		"pumpkin-headed",
		"dullahan",
		"skull-head",
		"skog",
		"scarecrow",
		"jackal",
		"lynx",
		"gryphon",
		"goo-creature",
		"imp",
		"owl",
		"sergal",
		"pig",
		"frog",
		"anubis",
		"borzoi",
		"sentient tank",
		"scarab",
		"monster",
		"lich",
		"ghoul",
		"tentacled thing"
		
	]
	return n[getRandomInt(n.length -1)];
}

function job(){
	var j = [
		"warrior",
		"ranger",
		"cleric",
		"wizard",
		"demon",
		"witch", 
		"automaton", 
		"knight", 
		"soldier",
		"clown",
		"jester",
		"zombie",
		"cyborg",
		"druid",
		"hunter",
		"dancer",
		"rogue",
		"scoundrel",
		"pirate",
		"bodybuilder",
		"prostitute",
		"beggar",
		"craftsman",
		"alchemist",
		"nomad",
		"wanderer",
		"traveller",
		"innkeeper",
		"scholar",
		"mercenary",
		"cavalier",
		"paladin",
		"healer",
		"detective",
		"gladiator",
		"performer",
		"samurai",
		"peasant",
		"cultist",
		"assassin",
		"bard",
		"monk",
		"pugilist",
		"gunslinger",
		"outlaw",
		"gamer",
		"nerd",
		"pilot",
		"chef",
		"drunkard",
		"barmaid",
		"hooters waiter/waitress",
		"farmer",
		"officeworker",
		"brawler",
		"musketeer",
		"duelist",
		"barista",
		"hipster",
		"model",
		"coward",
		"berserker",
		"barbarian",
		"king",
		"queen",
		"seducer",
		"villain",
		"hero",
		"scientist",
		"hag",
		"geezer",
		"fisherman",
		"woodcutter",
		"hermit",
		"stonemason",
		"herbalist",
		"laborer",
		"officer",
		"sheriff",
		"maid",
		"butler",
		"fiend",
		"punk",
		"librarian",
		"vigilante",
		"artisan",
		"veteran",
		"spy",
		"smuggler",
		"outlander",
		"entertainer",
		"athlete",
		"alcolyte",
		"ward",
		"fanatic",
		"bandit",
		"merchant",
		"heir apparent",
		"brat",
		"angel",
		"sailor",
		"captain",
		"actor/actress",
		"blacksmith",
		"monster-hunter",
		"killer",
		"werewolf",
		"explorer",
		"reporter",
		"swordsman",
		"abberation",
		"sludge-sifter",
		"city guard",
		"beekeeper",
		"acrobat",
		"contortionist",
		"snake-oil salesman",
		"swindler",
		"socialite",
		"with big naturals",
		"with a flat chest",
		"wearing bondage gear",
		"wearing pilot goggles",
		"with very long hair",
		"with a bobcut",
		"with a peaceful vibe",
		"with visible prosthesis",
		"wearing a kimono",
		"wearing a suit",
		"wearing a onesie costume pajama",
		"wearing thigh highs",
		"wearing a meme outfit",
		"wearing strapped overalls but no shirt",
		"wearing sneakers and nothing else",
		"wearing a cloak",
		"wearing a poncho",
		"wearing plate armor",
		"in a meme pose",
		"wearing a desertpunk outfit",
		"wearing a swimsuit",
		"wearing a cool mask",
		"from the wild west",
		"from feudal japan",
		"from renaissance europe",
		"from a souls-like setting",
		"from a high-fantasy setting",
		"from a low-fantasy setting",
		"pushed to their limit",
		"crashing out",
		"at their last stand",
		"at their lowest point",
		"that just had a shocking revelation",
		"in a jojo pose",
		"in a twisting pose",
		"flexing their muscles",
		"jumping into the air",
		"meditating"
		
		
		
	]
	return j[getRandomInt(j.length -1)];
}


function prefix(){
    prefixes = [
        "I think you should draw a",
        "What about a",
        "You could draw a",
        "How about a",
		"Draw a",
		"Draw some kind of",
		"Hmm... a",
		"Let's see a",
		"Perhaps a"
    ];

    return prefixes[getRandomInt(prefixes.length -1)];
}

function draw(){
	return (prefix() + " " + descriptor() + " " + noun() + " " + job());
}

function getRandomInt(max) {
    return Math.floor(Math.random() * max);
}

module.exports = {
    data: new SlashCommandBuilder()
        .setName('draw')
        .setDescription("Low-Quality drawing suggestions for indecisive artists"),
    async execute(interaction) {
      var action = interaction.options.getString('action');
      await interaction.reply(draw());
    },
};