const { SlashCommandBuilder } = require('@discordjs/builders');

function suntzu(){
    quotes = [
        "You are not allowed to drink battery acid",
        "wow big bat ears yum yum a meal for me?",
        "when are they adding the god damn NURGLINGS!!",
        "u should look at northern canada on google earth sometime",
        "sounds like a fat load of wasted time!",
        "I dont think a taco would kill an 17th century orphan but I do think one of those 2k plus calorie oreo milkshakes would because their body would go into shock from not being able to process the concentrated caloric value due to malnutrition",
        "guoh loves not playing games",
        "discord just crashes when you have a stream open and try to do anything else",
        "this is like the British stealing from the cultures they colonized and putting those artefacts in their museums",
        "isnt the ball pool of piss a tumblr museum artefact though",
        "how could a background characters lore be dissapointing",
        "why are we not downloading dawn of the tiberium age instead of looking at the worst poster to ever use social media",
        "goodnight sloppy",
        "Im just using the power of my acute inference and deduction skills",
        "hmm I should draw one of those fake mobile game spam ads with veka in a bathing suit",
        "the piss porn universe is the setting of Urge",
        "see the difference is you mean it only semi literally, whereas I mean what I said 100% literally",
        "damn, this is like having an ancient cursed toad statue that will answer any question truthfully as long as it is about something you have no use for",
        "its not the size thats the issue, its the balls being an oval",
        "guoh you are such a silly bog guy",
        "ABS (always be shitted)",
        "like her boobs are filled with lots of hot gas and they get super huge",
        "sex dungeons are despite the name not very sexy",
        "when girl is embarrassed, that's when im fairest",
        "No, i don't think I've ever drawn an honest-to-god ratbat-ass aeromorph",
        "bingbar???",
        "see now that ive given you a real problem to deal with you forgot about all that other stuff",
        "bob Im harassing joe on twitter what should I tell him",
        "cuck is such a fearsome word innit",
        "another super goddamn good trader joes junk food discovered",
        "I don't like the fandom enough to give them content",
        "Damn my feet are cold I should put socks on",
        "i love runescape the game but it is also populated by extremely deranged people",
        "These words will make your balls cease function for a full 24 hours or your money back",
        "do NOT turn waga upside down Worst mistake of my life",
        "Oh gee I sure hope no horny werewolf catches me",
        "time spent playing fortnite is time spent not playing LoL",
        "In prison just thinking about cats...",
        "I intercept this dog because it is good and now it's for me",
        "I am not a master of the anime booba but I will try my best",
        "a toe ring is like the choker of the foot",
	    "I dont think the body of a child would stop a nuclear missile",
        "people are just not willing to do isis over minor stuff yet",
        "AAAHHH LOOOK OUT GUOHHH AAAHH",
        "your vile spire is looking quite putrid today",
        "I doubt you would ever be able to guess what nsfw art I draw next, because honestly I dont even know most of the time. I simply get taken by an evil spirit and it happens",
        "a game funded by the russian government will never have hot slutty male characters",
        "a toe ring is like the choker of the foot",
        "I need to find a polite way to tell them this looks like ass",
        "Still mad that the Starbucks dragon drink did not tf me into a dragon",
        "Not saying this is tasteless but wow",
        "Idk I am torn between some kind of underboob crop top or a leotard",
        "Ain't no way I can put the mommy milkers squad out on display...",
        "brb gotta drill holes in  my wall",
        "If you shaved him do you think he'd look like a regular kobold or some kind of wrinkly pink hairless freak",
        "'Level drains u teehee",
        "reported for being bad at video games",
        "Who would be so knavish to do such terrible things...",
        "'That is the only comfort to me",
        "youve said this a lot",
        "'ah, well, gomonkul scamper upon you then",
        "thats my new hot term for dry humping",
        "wow just like real life",
        "huhuh im mr been huhuh gughhh",
        "I was just flicking the god switch on and off on my god laser pointed at her house",
        "atted the wrong person award",
        "I need my coitus silver to live",
        "im trying to find a good reference image of the ship from titan A.E. for you",
        "not as cool as the ships from titan A.E.",
        "look away this slutula is too much for you to handle",
        "you cannot get death crystals from old men, death crystals only appear in dead things",
        "bob kill him",
        "plato owns your ass",
        "fuuuucckkkk hggghhhhh",
        "bro is complaining about the free aphids I put on his coli",
        "bugs are eating it now",
        "they were designed in a lab for getting pinched and pulled",
        "sergals can just do that",
        "I remember being like 12 and my dad repeatedly killing r2d2 or Yoda because he thought the sounds were funny",
        "I didnt even notice the egg flaps",
        "papa needs his shroomies",
        "superr marioooo go fuck yourself wahooo ",
        "me when my boss asks me where my mortal flesh is",
        "It needs its funko pop",
        "i need more faces of sinister enjoyment",
        "Attack",
        "hoe bug sex creatures",
        "baffling and insane kind of",
        "you probably shouldn't read too much into it",
        "I thought it was neat, but I just didn't like the two minutes of baby crying noises for the end sequence",
        "drawing porn is like getting cummed on all day or some'n, I dunno",
        "it's pronounced 'yerma' I think",
        "I'm gonna pull some strings and get gaben and toby fox in the server so we can settle this",
        "just sitting there and shootin' goo?",
        "you can be a hater at any age",
        "circumcision is worse than bombing hydroelectric dams really",
        "I can never know if people who love it are aware of butthole or not....",
        "(happy souls voice) HORSE BUT HOLE?!",
        "the game has nipples",
        "I have a breeding pair of Jade dragons now.",
        "wear a clown hat and also make your topology seen to the world",
        "God could read your mind so the only reason he would turn you into a horse was because he thinks you deserve to suffer"
    ];

    return quotes[getRandomInt(quotes.length -1)];
}

function getRandomInt(max) {
    return Math.floor(Math.random() * max);
  }

module.exports = {
    data: new SlashCommandBuilder()
        .setName('suntzu')
        .setDescription('Did he say that?'),
    async execute(interaction) {
      var action = interaction.options.getString('action');
      await interaction.reply(suntzu());
    },
};
